language: cpp
compiler:
  - gcc
  - clang

before_install:
 - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
 - sudo apt-get update -qq
 - sudo apt-get install cmake
 - sudo pip install cpp-coveralls

script: cmake ./ && make

after_success: coveralls --exclude lib --exclude tests --gcov-options '\-lp'

